"""Initial migration

Revision ID: 2fecffcca4c9
Revises: 
Create Date: 2024-07-28 18:24:18.016722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fecffcca4c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_location', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
